### ISSUE TITLE
Downloading the genome gives Permission Denied errors on Windows

### ISSUE THREAD

**Issue by Melnorme1984** [lrgr/explosig-data#1]
It's due to this this line in the `download_human_genomes()` method in genomes.py:

`with tempfile.NamedTemporaryFile(mode='w') as temp:`

To fix it, you need to add a `delete=False` argument, like this:

`with tempfile.NamedTemporaryFile(mode='w', delete=False) as temp:`

The same problem exists in genes.py as well.

**Comment by keller-mark** [comment]
Thanks for the heads up. Just pushed version `0.0.5` to pypi. Please let me know if you encounter any other issues.
